version: '3'
services:
  project:
    build: ./docker/project
    #restart: always
    volumes:
      - ./project:/project
    working_dir: /project
    ports: 
      - ${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}
    # labels:
    #   - traefik.enable=true
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - db
      - exterior

  mongodb:
    image: mongo:bionic
    volumes:
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/data/db/:/data/db/
      - ./mongodb/data/log/:/var/log/mongodb/
      - ./mongodb/initdb.d/:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    networks:
      - db

networks:
  db:
    internal: true
  exterior:
    internal: false